# Generated by Django 5.0.1 on 2024-01-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_right_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api/images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='build_right_api.service')),
            ],
        ),
    ]
