# Generated by Django 5.0.1 on 2024-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_right_api', '0003_request_alter_serviceimage_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
