# Generated by Django 5.0.1 on 2024-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_right_api', '0004_remove_request_status_request_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
