# Generated by Django 5.0.1 on 2024-01-29 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_right_api', '0006_request_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api/images')),
                ('state', models.CharField(choices=[('B', 'Before'), ('A', 'After')], max_length=1)),
                ('Review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_image', to='build_right_api.review')),
            ],
        ),
    ]
