# Generated by Django 5.0.1 on 2024-01-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_right_api', '0007_reviewimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='Review',
            new_name='review',
        ),
    ]
