# Generated by Django 5.0.1 on 2024-01-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_right_api', '0008_rename_review_reviewimage_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='message',
            new_name='description',
        ),
    ]
